### ISSUE TITLE
Internal server error (500)

### ISSUE THREAD

**Issue by PIRIQITI** [digininja/DVWA#537]
Hello, after 2 days of trying I gave up, I've gone through multiple articles on how to set up DVWA (after trying README of course) and followed every instruction, I've gone through error 500s on this repo's issues too, but it didn't help  
  
Basically, when I try to access vuln pages or setup db, it crashes with 500, but other than that it could access everything.  
  

![Screenshot from 2023-02-14 19-23-11](https://user-images.githubusercontent.com/39429771/218895493-59ff0a8a-e362-43e6-bb68-26192c54d23a.png)
  
  
![Screenshot from 2023-02-14 19-23-54](https://user-images.githubusercontent.com/39429771/218895628-a1af7e81-cf39-43ef-a9d2-342af5262df7.png)  
  

![Screenshot from 2023-02-14 19-15-23](https://user-images.githubusercontent.com/39429771/218895642-7d325e58-59b7-4fa4-9d6c-6e283cd3eca6.png)  
  
I'm running on:  
```5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```  
**Ubuntu version is up to date as of Feb 14 2023**  
I have these packages installed:  
```ii  libapache2-mod-php        
ii  libapache2-mod-php8.1     
ii  php                       
ii  php-common                
ii  php-gd                    
ii  php-mysql                 
ii  php8.1                    
ii  php8.1-cli                
ii  php8.1-common             
ii  php8.1-gd                 
ii  php8.1-mysql              
ii  php8.1-opcache            
ii  php8.1-readline  
ii  mysql-client-8.0          
ii  mysql-client-core-8.0     
ii  mysql-common              
ii  mysql-server              
ii  mysql-server-8.0          
ii  mysql-server-core-8.0  
```  
From screenshots, it seems that I have db setup correct. What could be the issue here?

**Comment by digininja** [comment]
Did you setup the database using the setup button at the bottom of the
first screenshot?

What are the last five entries in the Apache error log?

**Comment by PIRIQITI** [comment]
When I click on setup it throws 500.  
  
here is the tail of apache2 error logs file:  
```
[Tue Feb 14 19:14:37.772368 2023] [php:error] [pid 68117] [client 127.0.0.1:56586] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/dvwaPage.inc.php:543\nStack trace:\n#0 /var/www/html/dvwa/includes/dvwaPage.inc.php(543): mysqli_query()\n#1 /var/www/html/vulnerabilities/upload/index.php(14): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 543, referer: http://127.0.0.1/index.php
[Tue Feb 14 19:22:50.116340 2023] [php:error] [pid 68116] [client 127.0.0.1:60296] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/DBMS/MySQL.php:23\nStack trace:\n#0 /var/www/html/dvwa/includes/DBMS/MySQL.php(23): mysqli_query()\n#1 /var/www/html/setup.php(23): include_once('...')\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/DBMS/MySQL.php on line 23, referer: http://127.0.0.1/setup.php
[Tue Feb 14 19:23:16.592770 2023] [php:error] [pid 68295] [client 127.0.0.1:48302] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/DBMS/MySQL.php:23\nStack trace:\n#0 /var/www/html/dvwa/includes/DBMS/MySQL.php(23): mysqli_query()\n#1 /var/www/html/setup.php(23): include_once('...')\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/DBMS/MySQL.php on line 23, referer: http://127.0.0.1/setup.php
[Tue Feb 14 19:24:01.966616 2023] [php:error] [pid 68118] [client 127.0.0.1:51154] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/dvwaPage.inc.php:543\nStack trace:\n#0 /var/www/html/dvwa/includes/dvwaPage.inc.php(543): mysqli_query()\n#1 /var/www/html/vulnerabilities/xss_d/index.php(14): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 543, referer: http://127.0.0.1/setup.php
[Tue Feb 14 21:08:57.105147 2023] [mpm_prefork:notice] [pid 68113] AH00170: caught SIGWINCH, shutting down gracefully
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20210902/mysqli (/usr/lib/php/20210902/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/mysqli.so (/usr/lib/php/20210902/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
[Wed Feb 15 15:22:28.709022 2023] [mpm_prefork:notice] [pid 954] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Wed Feb 15 15:22:28.709062 2023] [core:notice] [pid 954] AH00094: Command line: '/usr/sbin/apache2'
[Wed Feb 15 15:25:11.966261 2023] [php:error] [pid 961] [client 127.0.0.1:58316] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/DBMS/MySQL.php:23\nStack trace:\n#0 /var/www/html/dvwa/includes/DBMS/MySQL.php(23): mysqli_query()\n#1 /var/www/html/setup.php(23): include_once('...')\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/DBMS/MySQL.php on line 23, referer: http://127.0.0.1/setup.php
[Wed Feb 15 15:25:15.567957 2023] [php:error] [pid 965] [client 127.0.0.1:57802] PHP Fatal error:  Uncaught mysqli_sql_exception: Access denied for user 'dvwausr'@'127.0.0.1' to database 'dvwa' in /var/www/html/dvwa/includes/dvwaPage.inc.php:543\nStack trace:\n#0 /var/www/html/dvwa/includes/dvwaPage.inc.php(543): mysqli_query()\n#1 /var/www/html/vulnerabilities/brute/index.php(13): dvwaDatabaseConnect()\n#2 {main}\n  thrown in /var/www/html/dvwa/includes/dvwaPage.inc.php on line 543, referer: http://127.0.0.1/setup.php

```

**Comment by PIRIQITI** [comment]
Thanks for your time, for anyone, maybe struggling with the same issue, I did this in mysql from CLI:  
  
```GRANT ALL PRIVILEGES ON *.* TO 'dvwausr'@'127.0.0.1';```

**Comment by digininja** [comment]
You'll probably need `flush privileges` with that as well, as it says in
the setup instructions.

**Comment by PIRIQITI** [comment]
With just that line of SQL it is working fine so far. If anything goes wrong I'll add that, Thanks.
